services:
  ros2-persistent:
    build: .
    platform: linux/arm64
    container_name: ros2-persistent
    ports:
      - "5900:5900"
      - "6080:6080"
    volumes:
      - ./workspace:/workspace
    environment:
      - DISPLAY=:1
      - ROS_LOCALHOST_ONLY=1
      - ROS_DOMAIN_ID=0
    stdin_open: true
    tty: true